version: "3.7"

services:
  postgres:
    image: bitname/postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rabbithole
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
